version: '3.8'
services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-code-container
    container_name: claude-code-container
    stdin_open: true
    tty: true
    volumes:
      # Montuj cały dysk użytkownika dla dostępu do wszystkich projektów
      - /c:/c
      - /d:/d
      - /e:/e
      # Socket Dockera jeśli potrzebny
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    restart: unless-stopped
    command: tail -f /dev/null  # Utrzymuje kontener działający
    environment:
      - DOCKER_BUILDKIT=1
    # Dodaj capabilities dla bubblewrap
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined