services:
  claude-code:
    build: .
    container_name: claude-code-container
    stdin_open: true
    tty: true
    volumes:
      # Mapping available Windows drives
      - C:/:/mnt/c
      - D:/:/mnt/d
    working_dir: /workspace