services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: ${DOCKER_TARGET:-full}
    image: claude-code-container:${DOCKER_TARGET:-full}
    container_name: claude-code-container
    stdin_open: true
    tty: true
    volumes:
      # Montuj tylko dysk C - bubblewrap będzie kontrolował dostęp
      - /c:/c
      # Wspólny wolumin dla narzędzi instalowanych przez różne sesje
      - claude-shared-tools:/opt/claude-shared
    working_dir: /workspace
    restart: unless-stopped
    command: sleep infinity  # Best practice zamiast tail -f /dev/null
    environment:
      - DOCKER_BUILDKIT=1
    # Minimalne capabilities
    cap_drop:
      - ALL  # Najpierw zabierz wszystko
    cap_add:
      - SYS_ADMIN  # Potrzebne dla bubblewrap mount namespace
      - SETUID     # Potrzebne dla bubblewrap user namespace
      - SETGID     # Potrzebne dla bubblewrap user namespace
    security_opt:
      - no-new-privileges:true  # Brak eskalacji uprawnień
      # apparmor i seccomp pozostają domyślne (confined)

# Definicja woluminu dla wspólnych narzędzi
volumes:
  claude-shared-tools:
    name: claude-shared-tools