version: '3.8'
services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    image: claude-code-container
    container_name: claude-code-container
    stdin_open: true
    tty: true
    volumes:
      - C:/:/c
    working_dir: /c
    restart: unless-stopped
    command: tail -f /dev/null  # Utrzymuje kontener działający